# Generated by Django 5.0.7 on 2024-09-11 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id_imovel', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_imovel', models.CharField(choices=[('casa', 'Casa'), ('apartamento', 'Apartamento')], max_length=20)),
                ('nome_proprietario', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('quantidade_quartos', models.PositiveIntegerField()),
                ('quantidade_suites', models.PositiveIntegerField()),
                ('quantidade_salas_estar', models.PositiveIntegerField()),
                ('vagas_garagem', models.PositiveIntegerField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=8)),
                ('armario_embutido', models.BooleanField()),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('imovel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app_imobiliaria.imovel')),
                ('quantidade_salas_jantar', models.PositiveIntegerField()),
                ('andar', models.PositiveIntegerField()),
                ('valor_condominio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('portaria_24h', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('imovel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app_imobiliaria.imovel')),
            ],
        ),
    ]
