# Generated by Django 5.0.7 on 2024-09-11 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_imobiliaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=255)),
                ('data_visita', models.DateField()),
                ('horario_visita', models.TimeField()),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_imobiliaria.imovel')),
            ],
        ),
    ]
