# Generated by Django 5.0.7 on 2024-09-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_imobiliaria', '0002_visita'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='imagem_imovel',
            field=models.ImageField(blank=True, null=True, upload_to='imoveis/'),
        ),
    ]
