# Generated by Django 5.0.7 on 2024-09-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_imobiliaria', '0003_imovel_imagem_imovel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='imagem_imovel',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/'),
        ),
    ]
