# Generated by Django 5.1.1 on 2024-09-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_imobiliaria', '0004_alter_imovel_imagem_imovel'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='valor_imovel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
